name: ❖ App - Check

on:
  workflow_call:

env:
  RUST_BACKTRACE: full

permissions:
  contents: read

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Install Rust ${{ inputs.version }}"
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ vars.RUST_VERSION }}
          components: clippy

      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: "Clippy"
        run: cargo clippy -- -D warnings

  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Install Rust ${{ inputs.version }}"
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ vars.RUST_VERSION }}
          components: rustfmt

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: "Check Formatting"
        run: cargo fmt -- --check

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Install Rust ${{ inputs.version }}"
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ vars.RUST_VERSION }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: "Unit Tests"
        run: cargo test --all-features
